---
# ansible role requirements
- name: powo.utils
  src: git+https://github.com/powo-roles/powo.utils.git
  version: master
- name: powo.rpmfusion
  src: git+https://github.com/powo-roles/powo.rpmfusion.git
  version: master
